import math

TEMP_OBJECT_K = 310
TEMP_BG_K = 293
DELTA_T_K = TEMP_OBJECT_K - TEMP_BG_K
ATMOSPHERE_TRANS = 0.85
LENS_TRANS = 0.9
NETD_MK = 50
FOV_H_DEG = 57
FOV_V_DEG = 44
PIXELS_H = 160
PIXELS_V = 120
IFOV_H_MRAD = FOV_H_DEG * 1000 / PIXELS_H
IFOV_V_MRAD = FOV_V_DEG * 1000 / PIXELS_V

SIGNAL_MK = DELTA_T_K * ATMOSPHERE_TRANS * LENS_TRANS * 1000
SNR_THERMAL = SIGNAL_MK / NETD_MK
TARGET_HEIGHT_M = 1.7
TARGET_WIDTH_M = 0.5
TARGET_THERMAL_AREA_M2 = TARGET_HEIGHT_M * TARGET_WIDTH_M
PIXELS_ON_TARGET = TARGET_THERMAL_AREA_M2 / (IFOV_H_MRAD * 1e-3 * 1.0)**2
JOHNSON_DET = 1.0
JOHNSON_REC = 4.0
JOHNSON_ID = 8.0

R_DET_M = TARGET_HEIGHT_M * PIXELS_H / (JOHNSON_DET * IFOV_H_MRAD * 1e-3 * PIXELS_H) * SNR_THERMAL / 10
R_DET_M = min(R_DET_M, 2000)
R_REC_M = R_DET_M / 4
R_ID_M = R_DET_M / 8

LIDAR_RANGE_M = 12
LIDAR_ANGULAR_RES_DEG = 0.5
LIDAR_POINTS = int(360 / LIDAR_ANGULAR_RES_DEG)
LIDAR_POINT_DENSITY_PER_M2 = LIDAR_POINTS / (math.pi * LIDAR_RANGE_M**2)
LIDAR_ACCURACY_MM = 30

ANEMOMETER_RANGE_MS = 0.5
ANEMOMETER_ACCURACY_MS = 0.3
WIND_CORRECTION_FACTOR = 0.85

GPS_ACCURACY_M = 2.5
GPS_HZ = 10
IMU_DRIFT_DEG_H = 0.5
FUSION_ACCURACY_M = math.sqrt(GPS_ACCURACY_M**2 + (IMU_DRIFT_DEG_H/3600)**2)

FLOW_SENSOR_ACCURACY_PCT = 1.43
SPRAY_DRIFT_WITH_CORRECTION_PCT = 8.0
SPRAY_DRIFT_WITHOUT_CORRECTION_PCT = 25.0
SAVING_DRIFT_PCT = SPRAY_DRIFT_WITHOUT_CORRECTION_PCT - SPRAY_DRIFT_WITH_CORRECTION_PCT

AREA_HA = 500
SPRAYINGS_PER_SEASON = 6
VOLUME_L_HA = 300
CHEMICAL_PRICE_RUB_L = 500
TOTAL_LITRES = AREA_HA * SPRAYINGS_PER_SEASON * VOLUME_L_HA
SAVED_LITRES = TOTAL_LITRES * SAVING_DRIFT_PCT / 100
SAVED_RUB = SAVED_LITRES * CHEMICAL_PRICE_RUB_L

MODULE_COST_RUB = 300000
PAYBACK_EVENTS = MODULE_COST_RUB / (SAVED_RUB / SPRAYINGS_PER_SEASON)

POWER_THERMAL_W = 1.5
POWER_LIDAR_W = 2.0
POWER_ANEMO_W = 0.1
POWER_GPS_W = 0.3
POWER_JETSON_W = 5.0
POWER_TOTAL_W = POWER_THERMAL_W + POWER_LIDAR_W + POWER_ANEMO_W + POWER_GPS_W + POWER_JETSON_W
BATTERY_WH = 50
BATTERY_H = BATTERY_WH / POWER_TOTAL_W

print("=== АэроСкан-4: Расчёт оптико-электронной системы БПЛА ===")
print()
print("--- Тепловизионный канал ---")
print(f"NETD: {NETD_MK} мК, ΔT: {DELTA_T_K} К")
print(f"SNR: {SNR_THERMAL:.1f}")
print(f"Обнаружение: {R_DET_M:.0f} м")
print(f"Распознавание: {R_REC_M:.0f} м")
print(f"Идентификация: {R_ID_M:.0f} м")
print()
print("--- LiDAR ---")
print(f"Дальность: {LIDAR_RANGE_M} м, точек: {LIDAR_POINTS}")
print(f"Плотность: {LIDAR_POINT_DENSITY_PER_M2:.1f} точек/м²")
print(f"Точность: ±{LIDAR_ACCURACY_MM} мм")
print()
print("--- Навигация ---")
print(f"GPS: ±{GPS_ACCURACY_M} м, {GPS_HZ} Гц")
print(f"IMU дрейф: {IMU_DRIFT_DEG_H}°/ч")
print(f"Слияние датчиков: ±{FUSION_ACCURACY_M:.2f} м")
print()
print("--- Коррекция распыла ---")
print(f"Дрейф без коррекции: {SPRAY_DRIFT_WITHOUT_CORRECTION_PCT}%")
print(f"Дрейф с коррекцией: {SPRAY_DRIFT_WITH_CORRECTION_PCT}%")
print(f"Экономия: {SAVING_DRIFT_PCT}%")
print(f"Сезон ({AREA_HA} га × {SPRAYINGS_PER_SEASON} обработок): {SAVED_LITRES:.0f} л = {SAVED_RUB/1e6:.2f} млн ₽")
print(f"Стоимость модуля: {MODULE_COST_RUB/1e3:.0f} тыс. ₽")
print(f"Окупаемость: {PAYBACK_EVENTS:.1f} обработок")
print()
print("--- Питание ---")
print(f"Потребление: {POWER_TOTAL_W:.1f} Вт")
print(f"Автономность: {BATTERY_H:.1f} ч")