import math
CAMERA_H = 1280
CAMERA_V = 800
FPS = 60
BASELINE_M = 0.06
FOCAL_LENGTH_PX = 800
DISPARITY_RANGE = 64
MAX_RANGE_M = BASELINE_M * FOCAL_LENGTH_PX / 2
MIN_RANGE_M = BASELINE_M * FOCAL_LENGTH_PX / DISPARITY_RANGE
DEPTH_RESOLUTION_AT_10M = 10**2 / (BASELINE_M * FOCAL_LENGTH_PX)
JETSON_GFLOPS = 472
YOLOV5_NANO_INFERENCE_MS = 25
STEREO_MATCHING_MS = 15
TOTAL_PIPELINE_MS = YOLOV5_NANO_INFERENCE_MS + STEREO_MATCHING_MS
EFFECTIVE_FPS = 1000 / TOTAL_PIPELINE_MS
DETECTION_RANGE_PERSON_M = 80
DETECTION_RANGE_DRONE_M = 150
POWER_W = 10
MASS_G = 250
COST = 200000
MARKET = 100000
DJI_COST = 500000
print("=== ЗрениеБПЛА-5 ===")
print(f"Камера: {CAMERA_H}×{CAMERA_V}, {FPS} fps")
print(f"Baseline: {BASELINE_M*100:.0f} см, max range: {MAX_RANGE_M:.0f} м")
print(f"Min range: {MIN_RANGE_M:.1f} м, разрешение глубины @10м: {DEPTH_RESOLUTION_AT_10M:.3f} м")
print(f"Pipeline: {TOTAL_PIPELINE_MS} мс ({EFFECTIVE_FPS:.0f} fps)")
print(f"Детекция: человек {DETECTION_RANGE_PERSON_M} м, БПЛА {DETECTION_RANGE_DRONE_M} м")
print(f"Масса: {MASS_G} г, стоимость: {COST/1e3:.0f} тыс. ₽")
print(f"Рынок: {MARKET} × {COST/1e3:.0f} тыс. = {MARKET*COST/1e9:.0f} млрд ₽")
